import dayjs from 'dayjs/esm';

import { ICard, NewCard } from './card.model';

export const sampleWithRequiredData: ICard = {
  id: '521b4355-f464-4153-a9ad-931ebb6bab52',
};

export const sampleWithPartialData: ICard = {
  id: 'd0032438-a951-43e5-a561-6be8bcd46ff2',
  predecessorCardId: '70d52d26-573b-4543-adda-3aeb68b99815',
  accountId: '39e7e95c-2b77-48bb-bb6a-63f5381ec8c8',
  personId: 'so now spirit',
  type: 'ChipAndPinAnonymous',
  referenceNumber: 'unfortunately or given',
  blockType: 'Stolen',
  blockedBy: 'pension astride',
  status: 'Active',
  embossingLastName: 'quantify arrogantly',
  embossingCompanyName: 'boo',
  limitDailyPurchase: 12844.75,
  limitMonthlyPurchase: 2392.53,
  secure3DEmail: 'behind until ravioli',
  secure3DOutOfBandEnabled: true,
  secure3DOutOfBandId: 'authorized incidentally colon',
  deliveryFirstName: 'though',
  deliveryCompanyName: 'worth',
  deliveryPostalCode: 'abaft fooey when',
  deliveryCity: 'lest',
  deliveryPhone: 'highly train ugh',
  deliveryTrackingNumber: 'successfully consequently',
  isEnrolledFor3DSecure: false,
  isDisposable: true,
  securityWithdrawalEnabled: false,
  securityInternetPurchaseEnabled: false,
  securityAllTimeLimitsEnabled: false,
  carrierType: 'Standard',
  createdAt: dayjs('2025-04-23T10:31'),
  updatedAt: dayjs('2025-04-22T14:13'),
  dispatchedAt: dayjs('2025-04-22T17:23'),
  notificationInstantSpendUpdateEnabled: true,
};

export const sampleWithFullData: ICard = {
  id: 'b5bb927f-3af5-4317-a66a-944be1e0cdf9',
  predecessorCardId: 'dd945188-38a9-4637-92e7-b8c0f6353760',
  accountId: 'b4911f9b-eaed-44eb-8c87-910a8262e7c7',
  personId: 'surprise across unless',
  externalId: 'fluctuate seldom straw',
  type: 'ChipAndPin',
  name: 'however lampoon illustrious',
  maskedCardNumber: 'seemingly cautiously',
  referenceNumber: 'circle diligently sternly',
  expiryDate: dayjs('2025-04-23T08:06'),
  blockType: 'BlockedByClient',
  blockedAt: dayjs('2025-04-23T05:09'),
  blockedBy: 'notwithstanding',
  status: 'Closing',
  embossingName: 'godfather playfully',
  embossingFirstName: 'pro',
  embossingLastName: 'especially throbbing',
  embossingCompanyName: 'whoever',
  limitDailyPurchase: 3133.83,
  limitDailyWithdrawal: 15420.81,
  limitMonthlyPurchase: 4200.52,
  limitMonthlyWithdrawal: 966.09,
  limitTransactionPurchase: 11706.45,
  secure3DType: 'SMSOTPAndStaticPassword',
  secure3DMobile: 'apt ethical',
  secure3DEmail: 'symbolise till',
  secure3DLanguageCode: 'ENG',
  secure3DOutOfBandEnabled: true,
  secure3DOutOfBandId: 'republican till cheese',
  deliveryFirstName: 'for vice mechanically',
  deliveryLastName: 'cleverly gloss',
  deliveryCompanyName: 'and ouch rigidly',
  deliveryAddress1: 'happily slowly accessorise',
  deliveryAddress2: 'amid shovel',
  deliveryPostalCode: 'at when ah',
  deliveryCity: 'task',
  deliveryCountryCode: 'GNB',
  deliveryDispatchMethod: 'Courier',
  deliveryPhone: 'even',
  deliveryTrackingNumber: 'around insignificant beneath',
  isEnrolledFor3DSecure: true,
  isCard3DSecureActivated: true,
  renewAutomatically: true,
  isDisposable: false,
  securityContactlessEnabled: false,
  securityWithdrawalEnabled: true,
  securityInternetPurchaseEnabled: true,
  securityOverallLimitsEnabled: true,
  securityAllTimeLimitsEnabled: false,
  personalizationProductCode: 'upon spark ew',
  carrierType: 'Standard',
  cardMetadataProfileId: 'yowza',
  activatedAt: dayjs('2025-04-22T14:02'),
  createdAt: dayjs('2025-04-22T18:02'),
  updatedAt: dayjs('2025-04-22T22:45'),
  closedAt: dayjs('2025-04-22T12:08'),
  closedBy: 'gosh cornet bludgeon',
  closeReason: 'ClosedBySystem',
  companyId: 'ffde4cfb-7ac2-481d-b3a1-eda0aceedec6',
  dispatchedAt: dayjs('2025-04-23T02:51'),
  notificationReceiptsReminderEnabled: true,
  notificationInstantSpendUpdateEnabled: false,
  disposableType: 'None',
};

export const sampleWithNewData: NewCard = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
