import dayjs from 'dayjs/esm';
import { CardType } from 'app/entities/enumerations/card-type.model';
import { BlockType } from 'app/entities/enumerations/block-type.model';
import { CardStatus } from 'app/entities/enumerations/card-status.model';
import { Secure3DType } from 'app/entities/enumerations/secure-3-d-type.model';
import { LanguageCode } from 'app/entities/enumerations/language-code.model';
import { CountryCode } from 'app/entities/enumerations/country-code.model';
import { DispatchMethod } from 'app/entities/enumerations/dispatch-method.model';
import { CarrierType } from 'app/entities/enumerations/carrier-type.model';
import { CardCloseReason } from 'app/entities/enumerations/card-close-reason.model';
import { DisposableType } from 'app/entities/enumerations/disposable-type.model';

export interface ICard {
  id: string;
  predecessorCardId?: string | null;
  accountId?: string | null;
  personId?: string | null;
  externalId?: string | null;
  type?: keyof typeof CardType | null;
  name?: string | null;
  maskedCardNumber?: string | null;
  referenceNumber?: string | null;
  expiryDate?: dayjs.Dayjs | null;
  blockType?: keyof typeof BlockType | null;
  blockedAt?: dayjs.Dayjs | null;
  blockedBy?: string | null;
  status?: keyof typeof CardStatus | null;
  embossingName?: string | null;
  embossingFirstName?: string | null;
  embossingLastName?: string | null;
  embossingCompanyName?: string | null;
  limitDailyPurchase?: number | null;
  limitDailyWithdrawal?: number | null;
  limitMonthlyPurchase?: number | null;
  limitMonthlyWithdrawal?: number | null;
  limitTransactionPurchase?: number | null;
  secure3DType?: keyof typeof Secure3DType | null;
  secure3DMobile?: string | null;
  secure3DEmail?: string | null;
  secure3DLanguageCode?: keyof typeof LanguageCode | null;
  secure3DOutOfBandEnabled?: boolean | null;
  secure3DOutOfBandId?: string | null;
  deliveryFirstName?: string | null;
  deliveryLastName?: string | null;
  deliveryCompanyName?: string | null;
  deliveryAddress1?: string | null;
  deliveryAddress2?: string | null;
  deliveryPostalCode?: string | null;
  deliveryCity?: string | null;
  deliveryCountryCode?: keyof typeof CountryCode | null;
  deliveryDispatchMethod?: keyof typeof DispatchMethod | null;
  deliveryPhone?: string | null;
  deliveryTrackingNumber?: string | null;
  isEnrolledFor3DSecure?: boolean | null;
  isCard3DSecureActivated?: boolean | null;
  renewAutomatically?: boolean | null;
  isDisposable?: boolean | null;
  securityContactlessEnabled?: boolean | null;
  securityWithdrawalEnabled?: boolean | null;
  securityInternetPurchaseEnabled?: boolean | null;
  securityOverallLimitsEnabled?: boolean | null;
  securityAllTimeLimitsEnabled?: boolean | null;
  personalizationProductCode?: string | null;
  carrierType?: keyof typeof CarrierType | null;
  cardMetadataProfileId?: string | null;
  activatedAt?: dayjs.Dayjs | null;
  createdAt?: dayjs.Dayjs | null;
  updatedAt?: dayjs.Dayjs | null;
  closedAt?: dayjs.Dayjs | null;
  closedBy?: string | null;
  closeReason?: keyof typeof CardCloseReason | null;
  companyId?: string | null;
  dispatchedAt?: dayjs.Dayjs | null;
  notificationReceiptsReminderEnabled?: boolean | null;
  notificationInstantSpendUpdateEnabled?: boolean | null;
  disposableType?: keyof typeof DisposableType | null;
}

export type NewCard = Omit<ICard, 'id'> & { id: null };
