package io.github.vsinkievic.mockwallesterapi.domain;

import java.util.UUID;

public class CardTestSamples {

    public static Card getCardSample1() {
        return new Card()
            .id(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4aa"))
            .predecessorCardId(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4aa"))
            .accountId(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4aa"))
            .personId(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4bb"))
            .externalId("externalId1")
            .name("name1")
            .maskedCardNumber("maskedCardNumber1")
            .referenceNumber("referenceNumber1")
            .blockedBy("blockedBy1")
            .embossingName("embossingName1")
            .embossingFirstName("embossingFirstName1")
            .embossingLastName("embossingLastName1")
            .embossingCompanyName("embossingCompanyName1")
            .secure3DMobile("secure3DMobile1")
            .secure3DEmail("secure3DEmail1")
            .secure3DOutOfBandId("secure3DOutOfBandId1")
            .deliveryFirstName("deliveryFirstName1")
            .deliveryLastName("deliveryLastName1")
            .deliveryCompanyName("deliveryCompanyName1")
            .deliveryAddress1("deliveryAddress11")
            .deliveryAddress2("deliveryAddress21")
            .deliveryPostalCode("deliveryPostalCode1")
            .deliveryCity("deliveryCity1")
            .deliveryPhone("deliveryPhone1")
            .deliveryTrackingNumber("deliveryTrackingNumber1")
            .personalizationProductCode("personalizationProductCode1")
            .cardMetadataProfileId("cardMetadataProfileId1")
            .closedBy("closedBy1")
            .companyId(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4aa"));
    }

    public static Card getCardSample2() {
        return new Card()
            .id(UUID.fromString("ad79f240-3727-46c3-b89f-2cf6ebd74367"))
            .predecessorCardId(UUID.fromString("ad79f240-3727-46c3-b89f-2cf6ebd74367"))
            .accountId(UUID.fromString("ad79f240-3727-46c3-b89f-2cf6ebd74367"))
            .personId(UUID.fromString("23d8dc04-a48b-45d9-a01d-4b728f0ad4bb"))
            .externalId("externalId2")
            .name("name2")
            .maskedCardNumber("maskedCardNumber2")
            .referenceNumber("referenceNumber2")
            .blockedBy("blockedBy2")
            .embossingName("embossingName2")
            .embossingFirstName("embossingFirstName2")
            .embossingLastName("embossingLastName2")
            .embossingCompanyName("embossingCompanyName2")
            .secure3DMobile("secure3DMobile2")
            .secure3DEmail("secure3DEmail2")
            .secure3DOutOfBandId("secure3DOutOfBandId2")
            .deliveryFirstName("deliveryFirstName2")
            .deliveryLastName("deliveryLastName2")
            .deliveryCompanyName("deliveryCompanyName2")
            .deliveryAddress1("deliveryAddress12")
            .deliveryAddress2("deliveryAddress22")
            .deliveryPostalCode("deliveryPostalCode2")
            .deliveryCity("deliveryCity2")
            .deliveryPhone("deliveryPhone2")
            .deliveryTrackingNumber("deliveryTrackingNumber2")
            .personalizationProductCode("personalizationProductCode2")
            .cardMetadataProfileId("cardMetadataProfileId2")
            .closedBy("closedBy2")
            .companyId(UUID.fromString("ad79f240-3727-46c3-b89f-2cf6ebd74367"));
    }

    public static Card getCardRandomSampleGenerator() {
        return new Card()
            .id(UUID.randomUUID())
            .predecessorCardId(UUID.randomUUID())
            .accountId(UUID.randomUUID())
            .personId(UUID.randomUUID())
            .externalId(UUID.randomUUID().toString())
            .name(UUID.randomUUID().toString())
            .maskedCardNumber(UUID.randomUUID().toString())
            .referenceNumber(UUID.randomUUID().toString())
            .blockedBy(UUID.randomUUID().toString())
            .embossingName(UUID.randomUUID().toString())
            .embossingFirstName(UUID.randomUUID().toString())
            .embossingLastName(UUID.randomUUID().toString())
            .embossingCompanyName(UUID.randomUUID().toString())
            .secure3DMobile(UUID.randomUUID().toString())
            .secure3DEmail(UUID.randomUUID().toString())
            .secure3DOutOfBandId(UUID.randomUUID().toString())
            .deliveryFirstName(UUID.randomUUID().toString())
            .deliveryLastName(UUID.randomUUID().toString())
            .deliveryCompanyName(UUID.randomUUID().toString())
            .deliveryAddress1(UUID.randomUUID().toString())
            .deliveryAddress2(UUID.randomUUID().toString())
            .deliveryPostalCode(UUID.randomUUID().toString())
            .deliveryCity(UUID.randomUUID().toString())
            .deliveryPhone(UUID.randomUUID().toString())
            .deliveryTrackingNumber(UUID.randomUUID().toString())
            .personalizationProductCode(UUID.randomUUID().toString())
            .cardMetadataProfileId(UUID.randomUUID().toString())
            .closedBy(UUID.randomUUID().toString())
            .companyId(UUID.randomUUID());
    }
}
